from __future__ import annotations

from .models import Fundamentals, IndustryProfile, StockProfile


DEFAULT_MACRO_CONTEXT = (
    "AI 인프라 투자, 전력 수요 증가, 자동화, 방산 지출, 비만/만성질환 치료제, "
    "공급망 재편, 금리 인하 기대와 경기 둔화 우려가 동시에 존재하는 환경"
)


INDUSTRIES: tuple[IndustryProfile, ...] = (
    IndustryProfile(
        name="AI 반도체 및 데이터센터",
        description="AI 모델 학습/추론 수요가 GPU, HBM, 네트워킹, 서버, 냉각 인프라 투자를 견인합니다.",
        news_terms=("AI chip", "GPU", "HBM", "data center", "accelerator", "semiconductor"),
        macro_terms=("AI", "data center", "automation", "cloud", "capex", "productivity"),
        tailwinds=(
            "대형 클라우드 기업의 AI 설비투자 확대",
            "고성능 메모리와 네트워킹 병목으로 공급자 협상력 강화",
            "기업용 AI 도입이 추론 수요로 이어질 가능성",
        ),
        risks=(
            "고평가 구간에서 실적 기대치가 조금만 낮아져도 변동성이 커질 수 있음",
            "미중 수출 규제와 공급망 병목",
            "클라우드 CAPEX 둔화 가능성",
        ),
    ),
    IndustryProfile(
        name="전력 인프라 및 에너지 장비",
        description="AI 데이터센터, 전기화, 제조업 리쇼어링이 송전망, 변압기, 전력 관리 장비 수요를 키웁니다.",
        news_terms=("power grid", "electricity demand", "transformer", "grid", "energy infrastructure"),
        macro_terms=("data center", "electrification", "reshoring", "power demand", "infrastructure"),
        tailwinds=(
            "데이터센터 전력 사용량 증가",
            "노후 전력망 교체와 송배전 투자",
            "산업 자동화와 전기화 추세",
        ),
        risks=(
            "금리 상승 시 인프라 투자 지연",
            "원자재 가격과 프로젝트 승인 지연",
            "정책 지원 축소 가능성",
        ),
    ),
    IndustryProfile(
        name="비만 치료제 및 바이오 플랫폼",
        description="GLP-1 계열 비만/당뇨 치료제와 관련 생산설비, 위탁생산, 헬스케어 플랫폼이 성장합니다.",
        news_terms=("GLP-1", "obesity drug", "diabetes drug", "weight loss drug", "biopharma"),
        macro_terms=("healthcare", "obesity", "aging", "chronic disease", "drug pricing"),
        tailwinds=(
            "비만 치료제 시장 확대",
            "보험 적용 확대와 적응증 확장 가능성",
            "바이오 생산설비와 공급망 투자",
        ),
        risks=(
            "약가 규제와 보험 적용 제한",
            "임상 실패 또는 부작용 이슈",
            "경쟁 약물 출시",
        ),
    ),
    IndustryProfile(
        name="방산 및 우주항공",
        description="지정학적 긴장과 국방 예산 증가가 항공, 미사일, 센서, 위성, 사이버 방산 수요를 뒷받침합니다.",
        news_terms=("defense spending", "missile", "aerospace", "satellite", "geopolitical risk"),
        macro_terms=("geopolitical", "security", "defense", "NATO", "space"),
        tailwinds=(
            "유럽과 아시아의 방위비 증가",
            "장기 수주잔고 기반의 매출 가시성",
            "위성/감시/사이버 영역의 예산 확대",
        ),
        risks=(
            "정권 교체와 예산 우선순위 변화",
            "프로젝트 원가 초과",
            "수출 승인과 규제 리스크",
        ),
    ),
    IndustryProfile(
        name="사이버보안",
        description="AI 확산, 클라우드 전환, 랜섬웨어 증가가 보안 플랫폼 지출을 구조적으로 키웁니다.",
        news_terms=("cybersecurity", "ransomware", "zero trust", "cloud security", "data breach"),
        macro_terms=("AI", "cloud", "security", "digital transformation", "regulation"),
        tailwinds=(
            "AI 기반 공격과 방어 수요 동반 증가",
            "클라우드/원격근무 환경의 보안 예산 확대",
            "규제 강화에 따른 필수 지출 성격",
        ),
        risks=(
            "SaaS 밸류에이션 압축",
            "플랫폼 통합 경쟁 심화",
            "대형 보안 사고 발생 시 신뢰 훼손",
        ),
    ),
)


STOCKS: tuple[StockProfile, ...] = (
    StockProfile(
        ticker="NVDA",
        name="NVIDIA",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="AI GPU, 네트워킹, CUDA 생태계를 함께 보유한 AI 인프라 대표 기업입니다.",
        fundamentals=Fundamentals(126.0, 61.9, 91.5, 17.2, 52.0, 35.0, 3_000_000_000_000),
        recent_issues=("차세대 GPU 공급 일정과 고객 CAPEX가 핵심 체크포인트",),
        risks=("고성장 기대가 주가에 상당 부분 반영", "수출 규제와 공급망 리스크"),
    ),
    StockProfile(
        ticker="AMD",
        name="Advanced Micro Devices",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="GPU/CPU 포트폴리오를 바탕으로 AI 가속기 시장의 2위권 대안으로 평가됩니다.",
        fundamentals=Fundamentals(13.8, 5.4, 2.5, 4.1, 120.0, 31.0, 250_000_000_000),
        recent_issues=("AI 가속기 매출 램프업 속도가 투자 포인트",),
        risks=("높은 밸류에이션", "AI GPU 생태계에서 선두와의 격차"),
    ),
    StockProfile(
        ticker="AVGO",
        name="Broadcom",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="AI 네트워킹, ASIC, 인프라 소프트웨어가 데이터센터 투자와 연결됩니다.",
        fundamentals=Fundamentals(43.9, 45.2, 28.1, 150.0, 80.0, 30.0, 650_000_000_000),
        recent_issues=("AI 네트워킹과 맞춤형 칩 수요가 성장축",),
        risks=("인수 이후 부채 부담", "고객 집중도"),
    ),
    StockProfile(
        ticker="TSM",
        name="Taiwan Semiconductor Manufacturing",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="첨단 공정 파운드리 선두로 AI 칩 수요의 핵심 공급망입니다.",
        fundamentals=Fundamentals(8.9, 42.6, 26.2, 24.0, 29.0, 22.0, 800_000_000_000),
        recent_issues=("첨단 공정 증설과 지정학 리스크가 동시에 존재",),
        risks=("대만 지정학 리스크", "대형 고객 의존도"),
    ),
    StockProfile(
        ticker="ACMR",
        name="ACM Research",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="반도체 습식 세정 장비에 특화된 중소형 장비 기업으로 첨단 공정 투자 확대의 후발 수혜를 노립니다.",
        fundamentals=Fundamentals(45.0, 18.0, 12.0, 20.0, 24.0, 18.0, 1_800_000_000),
        recent_issues=("중국 및 글로벌 반도체 장비 투자 회복이 실적 민감도를 좌우",),
        risks=("중국 매출 비중", "장비 투자 사이클 변동"),
    ),
    StockProfile(
        ticker="CRDO",
        name="Credo Technology",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="AI 데이터센터의 고속 연결과 액티브 전기 케이블 수요에 노출된 소형 고성장 반도체 연결 기업입니다.",
        fundamentals=Fundamentals(63.0, -14.0, -8.0, 5.0, None, 95.0, 12_000_000_000),
        recent_issues=("AI 클러스터 네트워킹 병목과 대형 고객 채택 속도가 핵심 변수",),
        risks=("고객 집중도", "수익성 전환 지연"),
    ),
    StockProfile(
        ticker="ETN",
        name="Eaton",
        industry="전력 인프라 및 에너지 장비",
        role="core",
        thesis="전력 관리 장비와 데이터센터 전기 인프라 수요의 직접 수혜주입니다.",
        fundamentals=Fundamentals(11.8, 20.3, 19.5, 46.0, 38.0, 28.0, 125_000_000_000),
        recent_issues=("데이터센터와 전기화 수주잔고가 주가 모멘텀의 핵심",),
        risks=("산업 경기 둔화", "고평가 논란"),
    ),
    StockProfile(
        ticker="PWR",
        name="Quanta Services",
        industry="전력 인프라 및 에너지 장비",
        role="core",
        thesis="송전망, 전력망 현대화, 재생에너지 연결 공사의 대표 인프라 기업입니다.",
        fundamentals=Fundamentals(22.4, 6.8, 14.1, 60.0, 52.0, 31.0, 45_000_000_000),
        recent_issues=("전력망 투자 사이클과 유틸리티 CAPEX가 성장 근거",),
        risks=("프로젝트 마진 변동", "인건비와 원자재 비용"),
    ),
    StockProfile(
        ticker="NXT",
        name="Nextracker",
        industry="전력 인프라 및 에너지 장비",
        role="adjacent",
        thesis="태양광 추적장치와 발전 효율 개선 장비를 공급하는 중형 성장 기업으로 전력 수요 확대와 연결됩니다.",
        fundamentals=Fundamentals(31.0, 17.0, 38.0, 12.0, 25.0, 20.0, 6_000_000_000),
        recent_issues=("유틸리티 태양광 프로젝트와 전력 수요 증가가 수주 흐름의 핵심",),
        risks=("태양광 프로젝트 지연", "정책 인센티브 변화"),
    ),
    StockProfile(
        ticker="GEV",
        name="GE Vernova",
        industry="전력 인프라 및 에너지 장비",
        role="adjacent",
        thesis="가스 터빈, 전력망, 풍력 장비를 보유한 전력 공급망 재편 수혜 후보입니다.",
        fundamentals=Fundamentals(6.2, 4.8, 7.4, 15.0, 68.0, 30.0, 90_000_000_000),
        recent_issues=("전력 수요 증가와 발전 장비 수요가 부각",),
        risks=("풍력 부문 수익성", "신규 상장 이후 변동성"),
    ),
    StockProfile(
        ticker="LLY",
        name="Eli Lilly",
        industry="비만 치료제 및 바이오 플랫폼",
        role="core",
        thesis="비만/당뇨 치료제 파이프라인과 생산능력 증설이 장기 성장의 핵심입니다.",
        fundamentals=Fundamentals(20.1, 31.0, 55.0, 170.0, 95.0, 43.0, 750_000_000_000),
        recent_issues=("GLP-1 계열 치료제 수요와 공급 확대가 실적을 좌우",),
        risks=("약가 압박", "높은 성장 기대가 반영된 밸류에이션"),
    ),
    StockProfile(
        ticker="NVO",
        name="Novo Nordisk",
        industry="비만 치료제 및 바이오 플랫폼",
        role="core",
        thesis="GLP-1 시장 선도 기업으로 비만 치료제 확대의 직접 수혜를 받습니다.",
        fundamentals=Fundamentals(31.2, 45.8, 88.0, 31.0, 38.0, 28.0, 520_000_000_000),
        recent_issues=("공급 부족 해소와 경쟁 약물 출시가 주요 변수",),
        risks=("경쟁 심화", "보험 적용과 가격 규제"),
    ),
    StockProfile(
        ticker="VRTX",
        name="Vertex Pharmaceuticals",
        industry="비만 치료제 및 바이오 플랫폼",
        role="adjacent",
        thesis="희귀질환 중심의 높은 수익성과 신약 파이프라인을 가진 방어적 성장주입니다.",
        fundamentals=Fundamentals(10.5, 44.0, 22.0, 6.0, 31.0, 25.0, 120_000_000_000),
        recent_issues=("파이프라인 확장성과 기존 치료제 독점력이 투자 포인트",),
        risks=("파이프라인 임상 실패", "특정 질환 매출 의존도"),
    ),
    StockProfile(
        ticker="LMT",
        name="Lockheed Martin",
        industry="방산 및 우주항공",
        role="core",
        thesis="전투기, 미사일, 우주 시스템을 보유한 미국 방산 대표 기업입니다.",
        fundamentals=Fundamentals(2.4, 12.0, 85.0, 260.0, 18.0, 17.0, 110_000_000_000),
        recent_issues=("미사일 방어와 항공 플랫폼 수주가 실적 안정성을 제공",),
        risks=("정부 예산 의존", "프로그램 원가 초과"),
    ),
    StockProfile(
        ticker="RTX",
        name="RTX",
        industry="방산 및 우주항공",
        role="core",
        thesis="방산 전자장비와 항공 엔진을 함께 보유해 국방/민항 회복에 모두 노출됩니다.",
        fundamentals=Fundamentals(6.2, 8.8, 8.5, 70.0, 42.0, 20.0, 160_000_000_000),
        recent_issues=("엔진 품질 비용과 방산 수주 회복이 함께 체크포인트",),
        risks=("엔진 리콜 비용", "항공 사이클 둔화"),
    ),
    StockProfile(
        ticker="PLTR",
        name="Palantir",
        industry="방산 및 우주항공",
        role="adjacent",
        thesis="정부/방산 데이터 분석과 AI 플랫폼 수요를 연결하는 고성장 소프트웨어 기업입니다.",
        fundamentals=Fundamentals(20.8, 15.6, 8.0, 5.0, 160.0, 70.0, 90_000_000_000),
        recent_issues=("AI 플랫폼 도입 속도와 정부 계약 확대가 주가 변수",),
        risks=("매우 높은 밸류에이션", "계약 성장률 둔화 가능성"),
    ),
    StockProfile(
        ticker="RKLB",
        name="Rocket Lab",
        industry="방산 및 우주항공",
        role="adjacent",
        thesis="소형 발사체와 위성 제조를 함께 보유한 우주항공 성장 기업으로 정부/상업 우주 수요에 노출됩니다.",
        fundamentals=Fundamentals(78.0, -50.0, -28.0, 18.0, None, None, 5_000_000_000),
        recent_issues=("발사 빈도, 위성 시스템 수주, 차세대 로켓 개발 일정이 주가 변수",),
        risks=("영업적자와 현금 소진", "발사 실패 또는 개발 지연"),
    ),
    StockProfile(
        ticker="PANW",
        name="Palo Alto Networks",
        industry="사이버보안",
        role="core",
        thesis="네트워크, 클라우드, 엔드포인트 보안을 통합하는 대형 보안 플랫폼 기업입니다.",
        fundamentals=Fundamentals(16.5, 8.5, 55.0, 30.0, 48.0, 36.0, 120_000_000_000),
        recent_issues=("플랫폼화 전략과 청구액 성장률이 주요 투자 포인트",),
        risks=("플랫폼 통합 과정의 단기 성장 둔화", "경쟁 심화"),
    ),
    StockProfile(
        ticker="CRWD",
        name="CrowdStrike",
        industry="사이버보안",
        role="core",
        thesis="클라우드 네이티브 엔드포인트 보안과 위협 인텔리전스에서 강점을 가집니다.",
        fundamentals=Fundamentals(33.1, 4.0, 6.5, 25.0, 95.0, 55.0, 95_000_000_000),
        recent_issues=("대형 장애 이후 고객 신뢰 회복과 플랫폼 확장이 핵심",),
        risks=("운영 사고 재발 가능성", "고성장 SaaS 밸류에이션 부담"),
    ),
    StockProfile(
        ticker="NET",
        name="Cloudflare",
        industry="사이버보안",
        role="adjacent",
        thesis="네트워크, 보안, 엣지 컴퓨팅을 결합한 플랫폼으로 개발자 생태계가 강점입니다.",
        fundamentals=Fundamentals(30.0, -3.0, -7.0, 160.0, None, 85.0, 35_000_000_000),
        recent_issues=("보안과 AI 엣지 서비스 확장이 장기 옵션",),
        risks=("수익성 개선 속도", "높은 매출배수"),
    ),
    StockProfile(
        ticker="005930.KS",
        name="삼성전자",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="메모리, HBM, 파운드리, 모바일 반도체를 보유한 한국 반도체 대표 기업입니다.",
        fundamentals=Fundamentals(16.0, 9.0, 8.0, 25.0, 18.0, 13.0, None, "KRW"),
        recent_issues=("HBM 경쟁력 회복과 메모리 업황 개선 속도가 핵심 체크포인트",),
        risks=("HBM 경쟁 심화", "메모리 가격 사이클 변동"),
        country="KR",
        currency="KRW",
        dart_stock_code="005930",
    ),
    StockProfile(
        ticker="000660.KS",
        name="SK하이닉스",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="HBM과 고성능 DRAM 수요에 직접 노출된 AI 메모리 핵심 기업입니다.",
        fundamentals=Fundamentals(40.0, 23.0, 20.0, 70.0, 16.0, 11.0, None, "KRW"),
        recent_issues=("HBM 공급능력과 고객사 다변화가 주가 변수",),
        risks=("메모리 사이클 급락", "설비투자 부담"),
        country="KR",
        currency="KRW",
        dart_stock_code="000660",
    ),
    StockProfile(
        ticker="267260.KS",
        name="HD현대일렉트릭",
        industry="전력 인프라 및 에너지 장비",
        role="core",
        thesis="변압기와 전력기기 수요 증가의 직접 수혜를 받는 한국 전력 장비 기업입니다.",
        fundamentals=Fundamentals(28.0, 15.0, 22.0, 90.0, 25.0, 18.0, None, "KRW"),
        recent_issues=("북미 전력망 투자와 데이터센터 전력 수요가 수주 모멘텀",),
        risks=("수주 피크아웃 우려", "원자재와 환율 변동"),
        country="KR",
        currency="KRW",
        dart_stock_code="267260",
    ),
    StockProfile(
        ticker="010120.KS",
        name="LS ELECTRIC",
        industry="전력 인프라 및 에너지 장비",
        role="adjacent",
        thesis="전력 자동화, 배전, 스마트팩토리 장비를 보유한 전력 인프라 연관 기업입니다.",
        fundamentals=Fundamentals(18.0, 9.0, 14.0, 110.0, 22.0, 16.0, None, "KRW"),
        recent_issues=("전력망 투자와 자동화 수요가 실적 방향을 좌우",),
        risks=("국내 설비투자 둔화", "경쟁 심화"),
        country="KR",
        currency="KRW",
        dart_stock_code="010120",
    ),
    StockProfile(
        ticker="033100.KQ",
        name="제룡전기",
        industry="전력 인프라 및 에너지 장비",
        role="adjacent",
        thesis="변압기와 전력기기 수요 확대에 노출된 중소형 전력 장비 기업으로 북미 전력망 투자 사이클을 추적합니다.",
        fundamentals=Fundamentals(75.0, 24.0, 32.0, 35.0, 18.0, 14.0, 800_000_000_000, "KRW"),
        recent_issues=("변압기 수출 단가와 북미 교체 수요 지속성이 핵심 체크포인트",),
        risks=("수주 피크아웃", "소형주 변동성"),
        country="KR",
        currency="KRW",
        dart_stock_code="033100",
    ),
    StockProfile(
        ticker="399720.KQ",
        name="가온칩스",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="시스템 반도체 디자인 솔루션을 제공하는 소형 성장 기업으로 AI/차량용 반도체 설계 수요를 추적합니다.",
        fundamentals=Fundamentals(38.0, 8.0, 10.0, 55.0, 45.0, 32.0, 700_000_000_000, "KRW"),
        recent_issues=("ASIC 설계 프로젝트 수주와 파운드리 생태계 확장이 성장 변수",),
        risks=("고객 프로젝트 지연", "높은 밸류에이션"),
        country="KR",
        currency="KRW",
        dart_stock_code="399720",
    ),
    StockProfile(
        ticker="095340.KQ",
        name="ISC",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="반도체 테스트 소켓과 부품을 공급하는 중소형 기업으로 고성능 칩 테스트 수요에 노출됩니다.",
        fundamentals=Fundamentals(22.0, 25.0, 18.0, 30.0, 35.0, 25.0, 1_500_000_000_000, "KRW"),
        recent_issues=("AI 반도체 테스트 수요와 고객사 CAPEX 회복이 관찰 포인트",),
        risks=("반도체 투자 사이클", "고객 집중도"),
        country="KR",
        currency="KRW",
        dart_stock_code="095340",
    ),
    StockProfile(
        ticker="012450.KS",
        name="한화에어로스페이스",
        industry="방산 및 우주항공",
        role="core",
        thesis="지상 방산, 항공엔진, 우주 사업을 보유한 한국 방산 대표 기업입니다.",
        fundamentals=Fundamentals(30.0, 8.0, 18.0, 140.0, 28.0, 20.0, None, "KRW"),
        recent_issues=("수출 방산 수주잔고와 납품 일정이 실적 가시성의 핵심",),
        risks=("수출 승인 리스크", "프로젝트 원가와 납기 리스크"),
        country="KR",
        currency="KRW",
        dart_stock_code="012450",
    ),
    StockProfile(
        ticker="064350.KS",
        name="현대로템",
        industry="방산 및 우주항공",
        role="adjacent",
        thesis="전차, 방산 플랫폼, 철도 시스템을 함께 보유한 방산 연관 기업입니다.",
        fundamentals=Fundamentals(15.0, 6.0, 11.0, 125.0, 24.0, 17.0, None, "KRW"),
        recent_issues=("방산 수출과 철도 프로젝트 수익성이 관찰 포인트",),
        risks=("프로젝트 마진 변동", "방산 수주 집중도"),
        country="KR",
        currency="KRW",
        dart_stock_code="064350",
    ),
    StockProfile(
        ticker="207940.KS",
        name="삼성바이오로직스",
        industry="비만 치료제 및 바이오 플랫폼",
        role="adjacent",
        thesis="글로벌 바이오의약품 위탁생산 수요에 노출된 한국 대표 CDMO 기업입니다.",
        fundamentals=Fundamentals(22.0, 31.0, 12.0, 40.0, 70.0, 45.0, None, "KRW"),
        recent_issues=("대형 생산설비 가동률과 신규 수주가 장기 성장 변수",),
        risks=("높은 밸류에이션", "설비 증설 후 가동률 리스크"),
        country="KR",
        currency="KRW",
        dart_stock_code="207940",
    ),
    StockProfile(
        ticker="068270.KS",
        name="셀트리온",
        industry="비만 치료제 및 바이오 플랫폼",
        role="adjacent",
        thesis="바이오시밀러와 신약 파이프라인을 가진 한국 바이오 대표 기업입니다.",
        fundamentals=Fundamentals(10.0, 25.0, 9.0, 45.0, 38.0, 28.0, None, "KRW"),
        recent_issues=("바이오시밀러 점유율과 신제품 출시 속도가 투자 포인트",),
        risks=("약가 압박", "파이프라인 임상/허가 리스크"),
        country="KR",
        currency="KRW",
        dart_stock_code="068270",
    ),
)
