from __future__ import annotations

from dataclasses import replace

from .models import (
    BeneficiaryIndustryProfile,
    Fundamentals,
    IndustryMarketProxy,
    IndustryProfile,
    StockProfile,
)


DEFAULT_MACRO_CONTEXT = (
    "AI 인프라 투자, 전력 수요 증가, 자동화, 방산 지출, 비만/만성질환 치료제, "
    "공급망 재편, 금리 인하 기대와 경기 둔화 우려가 동시에 존재하는 환경"
)


def _proxy(ticker: str, name: str, role: str, weight: float = 1.0) -> IndustryMarketProxy:
    return IndustryMarketProxy(ticker=ticker, name=name, role=role, weight=weight)


INDUSTRIES: tuple[IndustryProfile, ...] = (
    IndustryProfile(
        name="AI 반도체 및 데이터센터",
        description="AI 모델 학습/추론 수요가 GPU, HBM, 네트워킹, 서버, 냉각 인프라 투자를 견인합니다.",
        news_terms=("AI chip", "GPU", "HBM", "data center", "accelerator", "semiconductor"),
        macro_terms=("AI", "data center", "automation", "cloud", "capex", "productivity"),
        tailwinds=(
            "대형 클라우드 기업의 AI 설비투자 확대",
            "고성능 메모리와 네트워킹 병목으로 공급자 협상력 강화",
            "기업용 AI 도입이 추론 수요로 이어질 가능성",
        ),
        risks=(
            "고평가 구간에서 실적 기대치가 조금만 낮아져도 변동성이 커질 수 있음",
            "미중 수출 규제와 공급망 병목",
            "클라우드 CAPEX 둔화 가능성",
        ),
    ),
    IndustryProfile(
        name="전력 인프라 및 에너지 장비",
        description="AI 데이터센터, 전기화, 제조업 리쇼어링이 송전망, 변압기, 전력 관리 장비 수요를 키웁니다.",
        news_terms=("power grid", "electricity demand", "transformer", "grid", "energy infrastructure"),
        macro_terms=("data center", "electrification", "reshoring", "power demand", "infrastructure"),
        tailwinds=(
            "데이터센터 전력 사용량 증가",
            "노후 전력망 교체와 송배전 투자",
            "산업 자동화와 전기화 추세",
        ),
        risks=(
            "금리 상승 시 인프라 투자 지연",
            "원자재 가격과 프로젝트 승인 지연",
            "정책 지원 축소 가능성",
        ),
    ),
    IndustryProfile(
        name="비만 치료제 및 바이오 플랫폼",
        description="GLP-1 계열 비만/당뇨 치료제와 관련 생산설비, 위탁생산, 헬스케어 플랫폼이 성장합니다.",
        news_terms=("GLP-1", "obesity drug", "diabetes drug", "weight loss drug", "biopharma"),
        macro_terms=("healthcare", "obesity", "aging", "chronic disease", "drug pricing"),
        tailwinds=(
            "비만 치료제 시장 확대",
            "보험 적용 확대와 적응증 확장 가능성",
            "바이오 생산설비와 공급망 투자",
        ),
        risks=(
            "약가 규제와 보험 적용 제한",
            "임상 실패 또는 부작용 이슈",
            "경쟁 약물 출시",
        ),
    ),
    IndustryProfile(
        name="방산 및 우주항공",
        description="지정학적 긴장과 국방 예산 증가가 항공, 미사일, 센서, 위성, 사이버 방산 수요를 뒷받침합니다.",
        news_terms=("defense spending", "missile", "aerospace", "satellite", "geopolitical risk"),
        macro_terms=("geopolitical", "security", "defense", "NATO", "space"),
        tailwinds=(
            "유럽과 아시아의 방위비 증가",
            "장기 수주잔고 기반의 매출 가시성",
            "위성/감시/사이버 영역의 예산 확대",
        ),
        risks=(
            "정권 교체와 예산 우선순위 변화",
            "프로젝트 원가 초과",
            "수출 승인과 규제 리스크",
        ),
    ),
    IndustryProfile(
        name="사이버보안",
        description="AI 확산, 클라우드 전환, 랜섬웨어 증가가 보안 플랫폼 지출을 구조적으로 키웁니다.",
        news_terms=("cybersecurity", "ransomware", "zero trust", "cloud security", "data breach"),
        macro_terms=("AI", "cloud", "security", "digital transformation", "regulation"),
        tailwinds=(
            "AI 기반 공격과 방어 수요 동반 증가",
            "클라우드/원격근무 환경의 보안 예산 확대",
            "규제 강화에 따른 필수 지출 성격",
        ),
        risks=(
            "SaaS 밸류에이션 압축",
            "플랫폼 통합 경쟁 심화",
            "대형 보안 사고 발생 시 신뢰 훼손",
        ),
    ),
)


BENEFICIARY_INDUSTRIES: tuple[BeneficiaryIndustryProfile, ...] = (
    BeneficiaryIndustryProfile(
        name="전력 인프라 및 에너지 장비",
        description="AI 데이터센터 증설이 전력 수요, 송배전망, 변압기와 전력 관리 장비 투자를 밀어 올립니다.",
        source_industry="AI 반도체 및 데이터센터",
        mechanism="AI 클러스터와 데이터센터 전력 밀도가 높아지면서 전력 공급, 배전, 백업 장비 병목이 먼저 드러납니다.",
        time_horizon="6~24개월",
        keywords=("power grid", "electricity demand", "transformer", "data center power", "전력망"),
        risks=("전력 프로젝트 승인 지연", "금리 상승 시 인프라 투자 지연"),
        connection_strength=94,
    ),
    BeneficiaryIndustryProfile(
        name="냉각/HVAC",
        description="고밀도 AI 서버가 액침냉각, 공조, 열관리 장비 수요를 키웁니다.",
        source_industry="AI 반도체 및 데이터센터",
        mechanism="GPU 랙 전력 밀도 상승은 냉각 설계와 열관리 설비 투자를 데이터센터 필수 CAPEX로 만듭니다.",
        time_horizon="6~18개월",
        keywords=("cooling", "liquid cooling", "HVAC", "thermal management", "data center cooling"),
        risks=("데이터센터 증설 속도 둔화", "표준 기술 변화에 따른 설비 교체 리스크"),
        connection_strength=88,
    ),
    BeneficiaryIndustryProfile(
        name="네트워킹",
        description="AI 학습/추론 클러스터 확장이 고속 스위치, 광통신, 연결 칩 수요로 이어집니다.",
        source_industry="AI 반도체 및 데이터센터",
        mechanism="GPU 수가 늘어날수록 병렬 처리와 데이터 이동을 위한 네트워킹 대역폭 투자가 함께 증가합니다.",
        time_horizon="3~18개월",
        keywords=("networking", "ethernet", "optical", "switch", "active electrical cable"),
        risks=("대형 고객 발주 집중도", "AI 서버 투자 사이클 변동"),
        connection_strength=90,
    ),
    BeneficiaryIndustryProfile(
        name="반도체 장비",
        description="첨단 공정과 HBM 투자 확대가 세정, 검사, 패키징 장비 수요를 보강합니다.",
        source_industry="AI 반도체 및 데이터센터",
        mechanism="AI 칩과 HBM 공급 병목은 파운드리와 메모리 업체의 선단 공정, 후공정, 장비 투자를 자극합니다.",
        time_horizon="9~30개월",
        keywords=("semiconductor equipment", "wafer fab equipment", "advanced packaging", "HBM", "반도체 장비"),
        risks=("반도체 CAPEX 사이클 둔화", "수출 규제와 고객 투자 지연"),
        connection_strength=84,
    ),
    BeneficiaryIndustryProfile(
        name="발전 장비",
        description="전력망 투자가 발전원 확충, 가스터빈, 원전, 분산전원 장비 수요로 이어질 수 있습니다.",
        source_industry="전력 인프라 및 에너지 장비",
        mechanism="송배전 병목 해소 후에는 실제 전력 공급 능력 확충과 안정적인 기저 전원 투자가 따라붙습니다.",
        time_horizon="12~36개월",
        keywords=("power generation", "gas turbine", "nuclear", "distributed generation", "발전 장비"),
        risks=("정책 승인과 환경 규제", "프로젝트 원가 초과"),
        connection_strength=82,
    ),
    BeneficiaryIndustryProfile(
        name="ESS",
        description="전력 수요 변동성과 재생에너지 연계가 배터리 저장장치 수요를 키웁니다.",
        source_industry="전력 인프라 및 에너지 장비",
        mechanism="전력망 부하가 커질수록 피크 대응과 재생에너지 출력 안정화를 위한 저장 설비가 필요해집니다.",
        time_horizon="9~30개월",
        keywords=("ESS", "battery storage", "grid storage", "energy storage", "배터리 저장"),
        risks=("배터리 가격 변동", "화재 안전 규제"),
        connection_strength=78,
    ),
    BeneficiaryIndustryProfile(
        name="전력 기자재",
        description="변압기, 차단기, 케이블, 배전반 등 전력망 확장에 필요한 기자재 수요가 늘어납니다.",
        source_industry="전력 인프라 및 에너지 장비",
        mechanism="전력 인프라 프로젝트가 늘면 고압/중압 장비와 현장 설치 기자재 주문이 후행합니다.",
        time_horizon="6~24개월",
        keywords=("switchgear", "cable", "transformer", "electrical equipment", "전력 기자재"),
        risks=("구리 등 원자재 가격 상승", "납기 지연"),
        connection_strength=86,
    ),
    BeneficiaryIndustryProfile(
        name="산업 자동화",
        description="전력 인프라 확충과 리쇼어링 투자가 공장 자동화, 전력 제어, 센서 수요와 연결됩니다.",
        source_industry="전력 인프라 및 에너지 장비",
        mechanism="전력 공급 안정성이 개선되면 제조 설비 증설과 자동화 투자가 더 쉽게 집행됩니다.",
        time_horizon="12~36개월",
        keywords=("industrial automation", "factory automation", "sensor", "controls", "산업 자동화"),
        risks=("제조업 경기 둔화", "고금리에 따른 설비투자 지연"),
        connection_strength=70,
    ),
    BeneficiaryIndustryProfile(
        name="CDMO",
        description="비만/당뇨 치료제 수요 확대가 위탁개발생산과 원료의약품 생산능력 투자로 번집니다.",
        source_industry="비만 치료제 및 바이오 플랫폼",
        mechanism="치료제 수요가 공급을 앞서면 생산 슬롯, 충전/포장, 원료의약품 설비 가치가 올라갑니다.",
        time_horizon="6~24개월",
        keywords=("CDMO", "contract manufacturing", "fill finish", "API manufacturing", "위탁생산"),
        risks=("주요 고객 의존도", "품질 이슈와 생산 지연"),
        connection_strength=86,
    ),
    BeneficiaryIndustryProfile(
        name="바이오 생산설비",
        description="바이오 의약품 증설이 배양, 정제, 충전, 멸균 장비와 소모품 수요를 키웁니다.",
        source_industry="비만 치료제 및 바이오 플랫폼",
        mechanism="GLP-1 공급 부족 해소와 적응증 확장은 제조 설비와 공정 장비 투자로 이어집니다.",
        time_horizon="9~30개월",
        keywords=("bioprocessing", "bioreactor", "fill finish", "sterile manufacturing", "바이오 설비"),
        risks=("임상/수요 기대 하향", "설비 과잉 투자"),
        connection_strength=82,
    ),
    BeneficiaryIndustryProfile(
        name="헬스케어 플랫폼",
        description="만성질환 관리와 비만 치료 접근성이 디지털 헬스, 원격관리, 보험/약국 플랫폼으로 확장됩니다.",
        source_industry="비만 치료제 및 바이오 플랫폼",
        mechanism="치료제 시장이 커질수록 처방 관리, 환자 유지, 부작용 모니터링과 결제/보험 워크플로가 중요해집니다.",
        time_horizon="12~36개월",
        keywords=("digital health", "healthcare platform", "chronic care", "telehealth", "헬스케어 플랫폼"),
        risks=("규제와 개인정보 보호", "보험 적용 범위 축소"),
        connection_strength=68,
    ),
    BeneficiaryIndustryProfile(
        name="위성통신",
        description="우주항공과 방산 예산 증가는 저궤도 위성, 통신 페이로드, 지상국 수요를 자극합니다.",
        source_industry="방산 및 우주항공",
        mechanism="정찰, 통신, 위치정보 수요가 늘면서 위성 제작과 발사, 지상 인프라 투자가 함께 증가합니다.",
        time_horizon="12~48개월",
        keywords=("satellite communication", "LEO", "space", "payload", "위성통신"),
        risks=("발사 지연과 기술 실패", "정부 예산 변동"),
        connection_strength=82,
    ),
    BeneficiaryIndustryProfile(
        name="사이버보안",
        description="군사 시스템과 정부 데이터의 디지털화가 보안 플랫폼 지출을 필수 예산으로 만듭니다.",
        source_industry="방산 및 우주항공",
        mechanism="방산 네트워크, 위성, 지휘통제 시스템이 연결될수록 침투 방어와 제로트러스트 보안 수요가 커집니다.",
        time_horizon="6~30개월",
        keywords=("cybersecurity", "zero trust", "ransomware", "cloud security", "사이버보안"),
        risks=("플랫폼 경쟁 심화", "대형 보안 사고에 따른 신뢰 훼손"),
        connection_strength=78,
    ),
    BeneficiaryIndustryProfile(
        name="첨단소재",
        description="항공/우주 플랫폼 고도화가 복합소재, 특수금속, 방열 소재 수요를 보강합니다.",
        source_industry="방산 및 우주항공",
        mechanism="미사일, 항공기, 우주체계 성능 향상은 경량화와 내열성 소재 채택을 동반합니다.",
        time_horizon="18~48개월",
        keywords=("advanced materials", "composite", "specialty metal", "thermal material", "첨단소재"),
        risks=("인증 주기 장기화", "원자재 공급 리스크"),
        connection_strength=66,
    ),
    BeneficiaryIndustryProfile(
        name="ID 관리",
        description="클라우드와 AI 보안 강화가 계정권한관리, 인증, 접근제어 지출로 이어집니다.",
        source_industry="사이버보안",
        mechanism="보안 사고의 상당 부분이 계정과 권한에서 시작되므로 제로트러스트 투자에서 ID 관리가 우선순위가 됩니다.",
        time_horizon="3~18개월",
        keywords=("identity management", "IAM", "zero trust", "authentication", "ID 관리"),
        risks=("대형 플랫폼 번들링", "고객 예산 통합"),
        connection_strength=82,
    ),
    BeneficiaryIndustryProfile(
        name="클라우드 보안",
        description="멀티클라우드와 AI 워크로드 확산이 클라우드 보안 태세관리와 데이터 보호 수요를 키웁니다.",
        source_industry="사이버보안",
        mechanism="AI 모델과 데이터가 클라우드에 올라갈수록 워크로드 보호, 권한, 설정 오류 탐지가 필수 통제가 됩니다.",
        time_horizon="3~24개월",
        keywords=("cloud security", "CNAPP", "CSPM", "workload security", "클라우드 보안"),
        risks=("보안 플랫폼 통합 경쟁", "SaaS 지출 둔화"),
        connection_strength=88,
    ),
    BeneficiaryIndustryProfile(
        name="데이터 거버넌스",
        description="AI 도입과 보안 규제가 데이터 분류, 접근통제, 감사 추적 수요를 늘립니다.",
        source_industry="사이버보안",
        mechanism="기업이 AI를 도입할수록 어떤 데이터가 어디에 쓰이는지 통제하고 감사할 수 있는 체계가 필요해집니다.",
        time_horizon="6~24개월",
        keywords=("data governance", "data privacy", "DLP", "compliance", "데이터 거버넌스"),
        risks=("도입 프로젝트 장기화", "규제 변화에 따른 제품 요구사항 변화"),
        connection_strength=76,
    ),
)


_BENEFICIARY_MARKET_PROXIES: dict[str, tuple[IndustryMarketProxy, ...]] = {
    "전력 인프라 및 에너지 장비": (
        _proxy("GRID", "First Trust Nasdaq Clean Edge Smart Grid Infrastructure ETF", "etf", 1.2),
        _proxy("PAVE", "Global X U.S. Infrastructure Development ETF", "etf", 1.1),
        _proxy("ETN", "Eaton", "representative", 1.0),
        _proxy("PWR", "Quanta Services", "representative", 1.0),
    ),
    "냉각/HVAC": (
        _proxy("CARR", "Carrier Global", "representative", 1.0),
        _proxy("TT", "Trane Technologies", "representative", 1.0),
        _proxy("JCI", "Johnson Controls", "representative", 0.9),
    ),
    "네트워킹": (
        _proxy("ANET", "Arista Networks", "representative", 1.1),
        _proxy("AVGO", "Broadcom", "representative", 1.0),
        _proxy("CRDO", "Credo Technology", "representative", 0.9),
    ),
    "반도체 장비": (
        _proxy("SMH", "VanEck Semiconductor ETF", "etf", 1.1),
        _proxy("SOXX", "iShares Semiconductor ETF", "etf", 1.1),
        _proxy("ASML", "ASML Holding", "representative", 1.0),
        _proxy("AMAT", "Applied Materials", "representative", 1.0),
        _proxy("LRCX", "Lam Research", "representative", 0.9),
    ),
    "발전 장비": (
        _proxy("GEV", "GE Vernova", "representative", 1.1),
        _proxy("VST", "Vistra", "representative", 1.0),
        _proxy("CEG", "Constellation Energy", "representative", 1.0),
        _proxy("BWXT", "BWX Technologies", "representative", 0.8),
    ),
    "ESS": (
        _proxy("LIT", "Global X Lithium & Battery Tech ETF", "etf", 1.1),
        _proxy("TSLA", "Tesla", "representative", 0.9),
        _proxy("FLNC", "Fluence Energy", "representative", 1.0),
        _proxy("NEE", "NextEra Energy", "representative", 0.8),
    ),
    "전력 기자재": (
        _proxy("GRID", "First Trust Nasdaq Clean Edge Smart Grid Infrastructure ETF", "etf", 1.2),
        _proxy("ETN", "Eaton", "representative", 1.0),
        _proxy("HUBB", "Hubbell", "representative", 1.0),
        _proxy("PWR", "Quanta Services", "representative", 0.9),
    ),
    "산업 자동화": (
        _proxy("ROBO", "ROBO Global Robotics and Automation ETF", "etf", 1.1),
        _proxy("ROK", "Rockwell Automation", "representative", 1.0),
        _proxy("EMR", "Emerson Electric", "representative", 0.9),
        _proxy("HON", "Honeywell", "representative", 0.9),
    ),
    "CDMO": (
        _proxy("IBB", "iShares Biotechnology ETF", "etf", 1.0),
        _proxy("XBI", "SPDR S&P Biotech ETF", "etf", 0.9),
        _proxy("207940.KS", "Samsung Biologics", "representative", 1.1),
        _proxy("WST", "West Pharmaceutical Services", "representative", 0.8),
    ),
    "바이오 생산설비": (
        _proxy("IBB", "iShares Biotechnology ETF", "etf", 0.9),
        _proxy("TMO", "Thermo Fisher Scientific", "representative", 1.1),
        _proxy("DHR", "Danaher", "representative", 1.0),
        _proxy("WST", "West Pharmaceutical Services", "representative", 0.9),
    ),
    "헬스케어 플랫폼": (
        _proxy("XLV", "Health Care Select Sector SPDR Fund", "etf", 1.0),
        _proxy("TDOC", "Teladoc Health", "representative", 0.8),
        _proxy("UNH", "UnitedHealth Group", "representative", 1.0),
        _proxy("CVS", "CVS Health", "representative", 0.8),
    ),
    "위성통신": (
        _proxy("ARKX", "ARK Space Exploration & Innovation ETF", "etf", 1.1),
        _proxy("RKLB", "Rocket Lab", "representative", 1.0),
        _proxy("IRDM", "Iridium Communications", "representative", 1.0),
        _proxy("LHX", "L3Harris Technologies", "representative", 0.9),
    ),
    "사이버보안": (
        _proxy("HACK", "ETFMG Prime Cyber Security ETF", "etf", 1.1),
        _proxy("CIBR", "First Trust Nasdaq Cybersecurity ETF", "etf", 1.1),
        _proxy("PANW", "Palo Alto Networks", "representative", 1.0),
        _proxy("CRWD", "CrowdStrike", "representative", 1.0),
        _proxy("NET", "Cloudflare", "representative", 0.8),
    ),
    "첨단소재": (
        _proxy("XLB", "Materials Select Sector SPDR Fund", "etf", 1.0),
        _proxy("ATI", "ATI", "representative", 1.0),
        _proxy("CRS", "Carpenter Technology", "representative", 0.9),
        _proxy("HWM", "Howmet Aerospace", "representative", 0.9),
    ),
    "ID 관리": (
        _proxy("CIBR", "First Trust Nasdaq Cybersecurity ETF", "etf", 1.0),
        _proxy("OKTA", "Okta", "representative", 1.1),
        _proxy("MSFT", "Microsoft", "representative", 0.9),
        _proxy("PANW", "Palo Alto Networks", "representative", 0.9),
    ),
    "클라우드 보안": (
        _proxy("CIBR", "First Trust Nasdaq Cybersecurity ETF", "etf", 1.0),
        _proxy("PANW", "Palo Alto Networks", "representative", 1.0),
        _proxy("CRWD", "CrowdStrike", "representative", 1.0),
        _proxy("NET", "Cloudflare", "representative", 0.9),
    ),
    "데이터 거버넌스": (
        _proxy("IGV", "iShares Expanded Tech-Software Sector ETF", "etf", 1.0),
        _proxy("ORCL", "Oracle", "representative", 0.9),
        _proxy("SNOW", "Snowflake", "representative", 1.0),
        _proxy("MSFT", "Microsoft", "representative", 0.9),
    ),
}


BENEFICIARY_INDUSTRIES = tuple(
    replace(profile, market_proxies=_BENEFICIARY_MARKET_PROXIES.get(profile.name, ()))
    for profile in BENEFICIARY_INDUSTRIES
)


STOCKS: tuple[StockProfile, ...] = (
    StockProfile(
        ticker="NVDA",
        name="NVIDIA",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="AI GPU, 네트워킹, CUDA 생태계를 함께 보유한 AI 인프라 대표 기업입니다.",
        fundamentals=Fundamentals(126.0, 61.9, 91.5, 17.2, 52.0, 35.0, 3_000_000_000_000),
        recent_issues=("차세대 GPU 공급 일정과 고객 CAPEX가 핵심 체크포인트",),
        risks=("고성장 기대가 주가에 상당 부분 반영", "수출 규제와 공급망 리스크"),
    ),
    StockProfile(
        ticker="AMD",
        name="Advanced Micro Devices",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="GPU/CPU 포트폴리오를 바탕으로 AI 가속기 시장의 2위권 대안으로 평가됩니다.",
        fundamentals=Fundamentals(13.8, 5.4, 2.5, 4.1, 120.0, 31.0, 250_000_000_000),
        recent_issues=("AI 가속기 매출 램프업 속도가 투자 포인트",),
        risks=("높은 밸류에이션", "AI GPU 생태계에서 선두와의 격차"),
    ),
    StockProfile(
        ticker="AVGO",
        name="Broadcom",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="AI 네트워킹, ASIC, 인프라 소프트웨어가 데이터센터 투자와 연결됩니다.",
        fundamentals=Fundamentals(43.9, 45.2, 28.1, 150.0, 80.0, 30.0, 650_000_000_000),
        recent_issues=("AI 네트워킹과 맞춤형 칩 수요가 성장축",),
        risks=("인수 이후 부채 부담", "고객 집중도"),
    ),
    StockProfile(
        ticker="TSM",
        name="Taiwan Semiconductor Manufacturing",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="첨단 공정 파운드리 선두로 AI 칩 수요의 핵심 공급망입니다.",
        fundamentals=Fundamentals(8.9, 42.6, 26.2, 24.0, 29.0, 22.0, 800_000_000_000),
        recent_issues=("첨단 공정 증설과 지정학 리스크가 동시에 존재",),
        risks=("대만 지정학 리스크", "대형 고객 의존도"),
    ),
    StockProfile(
        ticker="ACMR",
        name="ACM Research",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="반도체 습식 세정 장비에 특화된 중소형 장비 기업으로 첨단 공정 투자 확대의 후발 수혜를 노립니다.",
        fundamentals=Fundamentals(45.0, 18.0, 12.0, 20.0, 24.0, 18.0, 1_800_000_000),
        recent_issues=("중국 및 글로벌 반도체 장비 투자 회복이 실적 민감도를 좌우",),
        risks=("중국 매출 비중", "장비 투자 사이클 변동"),
    ),
    StockProfile(
        ticker="CRDO",
        name="Credo Technology",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="AI 데이터센터의 고속 연결과 액티브 전기 케이블 수요에 노출된 소형 고성장 반도체 연결 기업입니다.",
        fundamentals=Fundamentals(63.0, -14.0, -8.0, 5.0, None, 95.0, 12_000_000_000),
        recent_issues=("AI 클러스터 네트워킹 병목과 대형 고객 채택 속도가 핵심 변수",),
        risks=("고객 집중도", "수익성 전환 지연"),
    ),
    StockProfile(
        ticker="ETN",
        name="Eaton",
        industry="전력 인프라 및 에너지 장비",
        role="core",
        thesis="전력 관리 장비와 데이터센터 전기 인프라 수요의 직접 수혜주입니다.",
        fundamentals=Fundamentals(11.8, 20.3, 19.5, 46.0, 38.0, 28.0, 125_000_000_000),
        recent_issues=("데이터센터와 전기화 수주잔고가 주가 모멘텀의 핵심",),
        risks=("산업 경기 둔화", "고평가 논란"),
    ),
    StockProfile(
        ticker="PWR",
        name="Quanta Services",
        industry="전력 인프라 및 에너지 장비",
        role="core",
        thesis="송전망, 전력망 현대화, 재생에너지 연결 공사의 대표 인프라 기업입니다.",
        fundamentals=Fundamentals(22.4, 6.8, 14.1, 60.0, 52.0, 31.0, 45_000_000_000),
        recent_issues=("전력망 투자 사이클과 유틸리티 CAPEX가 성장 근거",),
        risks=("프로젝트 마진 변동", "인건비와 원자재 비용"),
    ),
    StockProfile(
        ticker="NXT",
        name="Nextracker",
        industry="전력 인프라 및 에너지 장비",
        role="adjacent",
        thesis="태양광 추적장치와 발전 효율 개선 장비를 공급하는 중형 성장 기업으로 전력 수요 확대와 연결됩니다.",
        fundamentals=Fundamentals(31.0, 17.0, 38.0, 12.0, 25.0, 20.0, 6_000_000_000),
        recent_issues=("유틸리티 태양광 프로젝트와 전력 수요 증가가 수주 흐름의 핵심",),
        risks=("태양광 프로젝트 지연", "정책 인센티브 변화"),
    ),
    StockProfile(
        ticker="GEV",
        name="GE Vernova",
        industry="전력 인프라 및 에너지 장비",
        role="adjacent",
        thesis="가스 터빈, 전력망, 풍력 장비를 보유한 전력 공급망 재편 수혜 후보입니다.",
        fundamentals=Fundamentals(6.2, 4.8, 7.4, 15.0, 68.0, 30.0, 90_000_000_000),
        recent_issues=("전력 수요 증가와 발전 장비 수요가 부각",),
        risks=("풍력 부문 수익성", "신규 상장 이후 변동성"),
    ),
    StockProfile(
        ticker="LLY",
        name="Eli Lilly",
        industry="비만 치료제 및 바이오 플랫폼",
        role="core",
        thesis="비만/당뇨 치료제 파이프라인과 생산능력 증설이 장기 성장의 핵심입니다.",
        fundamentals=Fundamentals(20.1, 31.0, 55.0, 170.0, 95.0, 43.0, 750_000_000_000),
        recent_issues=("GLP-1 계열 치료제 수요와 공급 확대가 실적을 좌우",),
        risks=("약가 압박", "높은 성장 기대가 반영된 밸류에이션"),
    ),
    StockProfile(
        ticker="NVO",
        name="Novo Nordisk",
        industry="비만 치료제 및 바이오 플랫폼",
        role="core",
        thesis="GLP-1 시장 선도 기업으로 비만 치료제 확대의 직접 수혜를 받습니다.",
        fundamentals=Fundamentals(31.2, 45.8, 88.0, 31.0, 38.0, 28.0, 520_000_000_000),
        recent_issues=("공급 부족 해소와 경쟁 약물 출시가 주요 변수",),
        risks=("경쟁 심화", "보험 적용과 가격 규제"),
    ),
    StockProfile(
        ticker="VRTX",
        name="Vertex Pharmaceuticals",
        industry="비만 치료제 및 바이오 플랫폼",
        role="adjacent",
        thesis="희귀질환 중심의 높은 수익성과 신약 파이프라인을 가진 방어적 성장주입니다.",
        fundamentals=Fundamentals(10.5, 44.0, 22.0, 6.0, 31.0, 25.0, 120_000_000_000),
        recent_issues=("파이프라인 확장성과 기존 치료제 독점력이 투자 포인트",),
        risks=("파이프라인 임상 실패", "특정 질환 매출 의존도"),
    ),
    StockProfile(
        ticker="LMT",
        name="Lockheed Martin",
        industry="방산 및 우주항공",
        role="core",
        thesis="전투기, 미사일, 우주 시스템을 보유한 미국 방산 대표 기업입니다.",
        fundamentals=Fundamentals(2.4, 12.0, 85.0, 260.0, 18.0, 17.0, 110_000_000_000),
        recent_issues=("미사일 방어와 항공 플랫폼 수주가 실적 안정성을 제공",),
        risks=("정부 예산 의존", "프로그램 원가 초과"),
    ),
    StockProfile(
        ticker="RTX",
        name="RTX",
        industry="방산 및 우주항공",
        role="core",
        thesis="방산 전자장비와 항공 엔진을 함께 보유해 국방/민항 회복에 모두 노출됩니다.",
        fundamentals=Fundamentals(6.2, 8.8, 8.5, 70.0, 42.0, 20.0, 160_000_000_000),
        recent_issues=("엔진 품질 비용과 방산 수주 회복이 함께 체크포인트",),
        risks=("엔진 리콜 비용", "항공 사이클 둔화"),
    ),
    StockProfile(
        ticker="PLTR",
        name="Palantir",
        industry="방산 및 우주항공",
        role="adjacent",
        thesis="정부/방산 데이터 분석과 AI 플랫폼 수요를 연결하는 고성장 소프트웨어 기업입니다.",
        fundamentals=Fundamentals(20.8, 15.6, 8.0, 5.0, 160.0, 70.0, 90_000_000_000),
        recent_issues=("AI 플랫폼 도입 속도와 정부 계약 확대가 주가 변수",),
        risks=("매우 높은 밸류에이션", "계약 성장률 둔화 가능성"),
    ),
    StockProfile(
        ticker="RKLB",
        name="Rocket Lab",
        industry="방산 및 우주항공",
        role="adjacent",
        thesis="소형 발사체와 위성 제조를 함께 보유한 우주항공 성장 기업으로 정부/상업 우주 수요에 노출됩니다.",
        fundamentals=Fundamentals(78.0, -50.0, -28.0, 18.0, None, None, 5_000_000_000),
        recent_issues=("발사 빈도, 위성 시스템 수주, 차세대 로켓 개발 일정이 주가 변수",),
        risks=("영업적자와 현금 소진", "발사 실패 또는 개발 지연"),
    ),
    StockProfile(
        ticker="PANW",
        name="Palo Alto Networks",
        industry="사이버보안",
        role="core",
        thesis="네트워크, 클라우드, 엔드포인트 보안을 통합하는 대형 보안 플랫폼 기업입니다.",
        fundamentals=Fundamentals(16.5, 8.5, 55.0, 30.0, 48.0, 36.0, 120_000_000_000),
        recent_issues=("플랫폼화 전략과 청구액 성장률이 주요 투자 포인트",),
        risks=("플랫폼 통합 과정의 단기 성장 둔화", "경쟁 심화"),
    ),
    StockProfile(
        ticker="CRWD",
        name="CrowdStrike",
        industry="사이버보안",
        role="core",
        thesis="클라우드 네이티브 엔드포인트 보안과 위협 인텔리전스에서 강점을 가집니다.",
        fundamentals=Fundamentals(33.1, 4.0, 6.5, 25.0, 95.0, 55.0, 95_000_000_000),
        recent_issues=("대형 장애 이후 고객 신뢰 회복과 플랫폼 확장이 핵심",),
        risks=("운영 사고 재발 가능성", "고성장 SaaS 밸류에이션 부담"),
    ),
    StockProfile(
        ticker="NET",
        name="Cloudflare",
        industry="사이버보안",
        role="adjacent",
        thesis="네트워크, 보안, 엣지 컴퓨팅을 결합한 플랫폼으로 개발자 생태계가 강점입니다.",
        fundamentals=Fundamentals(30.0, -3.0, -7.0, 160.0, None, 85.0, 35_000_000_000),
        recent_issues=("보안과 AI 엣지 서비스 확장이 장기 옵션",),
        risks=("수익성 개선 속도", "높은 매출배수"),
    ),
    StockProfile(
        ticker="005930.KS",
        name="삼성전자",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="메모리, HBM, 파운드리, 모바일 반도체를 보유한 한국 반도체 대표 기업입니다.",
        fundamentals=Fundamentals(16.0, 9.0, 8.0, 25.0, 18.0, 13.0, None, "KRW"),
        recent_issues=("HBM 경쟁력 회복과 메모리 업황 개선 속도가 핵심 체크포인트",),
        risks=("HBM 경쟁 심화", "메모리 가격 사이클 변동"),
        country="KR",
        currency="KRW",
        dart_stock_code="005930",
    ),
    StockProfile(
        ticker="000660.KS",
        name="SK하이닉스",
        industry="AI 반도체 및 데이터센터",
        role="core",
        thesis="HBM과 고성능 DRAM 수요에 직접 노출된 AI 메모리 핵심 기업입니다.",
        fundamentals=Fundamentals(40.0, 23.0, 20.0, 70.0, 16.0, 11.0, None, "KRW"),
        recent_issues=("HBM 공급능력과 고객사 다변화가 주가 변수",),
        risks=("메모리 사이클 급락", "설비투자 부담"),
        country="KR",
        currency="KRW",
        dart_stock_code="000660",
    ),
    StockProfile(
        ticker="267260.KS",
        name="HD현대일렉트릭",
        industry="전력 인프라 및 에너지 장비",
        role="core",
        thesis="변압기와 전력기기 수요 증가의 직접 수혜를 받는 한국 전력 장비 기업입니다.",
        fundamentals=Fundamentals(28.0, 15.0, 22.0, 90.0, 25.0, 18.0, None, "KRW"),
        recent_issues=("북미 전력망 투자와 데이터센터 전력 수요가 수주 모멘텀",),
        risks=("수주 피크아웃 우려", "원자재와 환율 변동"),
        country="KR",
        currency="KRW",
        dart_stock_code="267260",
    ),
    StockProfile(
        ticker="010120.KS",
        name="LS ELECTRIC",
        industry="전력 인프라 및 에너지 장비",
        role="adjacent",
        thesis="전력 자동화, 배전, 스마트팩토리 장비를 보유한 전력 인프라 연관 기업입니다.",
        fundamentals=Fundamentals(18.0, 9.0, 14.0, 110.0, 22.0, 16.0, None, "KRW"),
        recent_issues=("전력망 투자와 자동화 수요가 실적 방향을 좌우",),
        risks=("국내 설비투자 둔화", "경쟁 심화"),
        country="KR",
        currency="KRW",
        dart_stock_code="010120",
    ),
    StockProfile(
        ticker="033100.KQ",
        name="제룡전기",
        industry="전력 인프라 및 에너지 장비",
        role="adjacent",
        thesis="변압기와 전력기기 수요 확대에 노출된 중소형 전력 장비 기업으로 북미 전력망 투자 사이클을 추적합니다.",
        fundamentals=Fundamentals(75.0, 24.0, 32.0, 35.0, 18.0, 14.0, 800_000_000_000, "KRW"),
        recent_issues=("변압기 수출 단가와 북미 교체 수요 지속성이 핵심 체크포인트",),
        risks=("수주 피크아웃", "소형주 변동성"),
        country="KR",
        currency="KRW",
        dart_stock_code="033100",
    ),
    StockProfile(
        ticker="399720.KQ",
        name="가온칩스",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="시스템 반도체 디자인 솔루션을 제공하는 소형 성장 기업으로 AI/차량용 반도체 설계 수요를 추적합니다.",
        fundamentals=Fundamentals(38.0, 8.0, 10.0, 55.0, 45.0, 32.0, 700_000_000_000, "KRW"),
        recent_issues=("ASIC 설계 프로젝트 수주와 파운드리 생태계 확장이 성장 변수",),
        risks=("고객 프로젝트 지연", "높은 밸류에이션"),
        country="KR",
        currency="KRW",
        dart_stock_code="399720",
    ),
    StockProfile(
        ticker="095340.KQ",
        name="ISC",
        industry="AI 반도체 및 데이터센터",
        role="adjacent",
        thesis="반도체 테스트 소켓과 부품을 공급하는 중소형 기업으로 고성능 칩 테스트 수요에 노출됩니다.",
        fundamentals=Fundamentals(22.0, 25.0, 18.0, 30.0, 35.0, 25.0, 1_500_000_000_000, "KRW"),
        recent_issues=("AI 반도체 테스트 수요와 고객사 CAPEX 회복이 관찰 포인트",),
        risks=("반도체 투자 사이클", "고객 집중도"),
        country="KR",
        currency="KRW",
        dart_stock_code="095340",
    ),
    StockProfile(
        ticker="012450.KS",
        name="한화에어로스페이스",
        industry="방산 및 우주항공",
        role="core",
        thesis="지상 방산, 항공엔진, 우주 사업을 보유한 한국 방산 대표 기업입니다.",
        fundamentals=Fundamentals(30.0, 8.0, 18.0, 140.0, 28.0, 20.0, None, "KRW"),
        recent_issues=("수출 방산 수주잔고와 납품 일정이 실적 가시성의 핵심",),
        risks=("수출 승인 리스크", "프로젝트 원가와 납기 리스크"),
        country="KR",
        currency="KRW",
        dart_stock_code="012450",
    ),
    StockProfile(
        ticker="064350.KS",
        name="현대로템",
        industry="방산 및 우주항공",
        role="adjacent",
        thesis="전차, 방산 플랫폼, 철도 시스템을 함께 보유한 방산 연관 기업입니다.",
        fundamentals=Fundamentals(15.0, 6.0, 11.0, 125.0, 24.0, 17.0, None, "KRW"),
        recent_issues=("방산 수출과 철도 프로젝트 수익성이 관찰 포인트",),
        risks=("프로젝트 마진 변동", "방산 수주 집중도"),
        country="KR",
        currency="KRW",
        dart_stock_code="064350",
    ),
    StockProfile(
        ticker="207940.KS",
        name="삼성바이오로직스",
        industry="비만 치료제 및 바이오 플랫폼",
        role="adjacent",
        thesis="글로벌 바이오의약품 위탁생산 수요에 노출된 한국 대표 CDMO 기업입니다.",
        fundamentals=Fundamentals(22.0, 31.0, 12.0, 40.0, 70.0, 45.0, None, "KRW"),
        recent_issues=("대형 생산설비 가동률과 신규 수주가 장기 성장 변수",),
        risks=("높은 밸류에이션", "설비 증설 후 가동률 리스크"),
        country="KR",
        currency="KRW",
        dart_stock_code="207940",
    ),
    StockProfile(
        ticker="068270.KS",
        name="셀트리온",
        industry="비만 치료제 및 바이오 플랫폼",
        role="adjacent",
        thesis="바이오시밀러와 신약 파이프라인을 가진 한국 바이오 대표 기업입니다.",
        fundamentals=Fundamentals(10.0, 25.0, 9.0, 45.0, 38.0, 28.0, None, "KRW"),
        recent_issues=("바이오시밀러 점유율과 신제품 출시 속도가 투자 포인트",),
        risks=("약가 압박", "파이프라인 임상/허가 리스크"),
        country="KR",
        currency="KRW",
        dart_stock_code="068270",
    ),
)
